#!/usr/bin/env ansible-playbook

- hosts: localhost
  become: yes

  vars:
    - HOME: "{{ ansible_env.HOME }}"

  vars_files:
    - secrets.yml

  tasks:
    - name: install private key
      copy:
        content: "{{ PRIVATE_SSH_KEY }}"
        dest: "{{ HOME }}/.ssh/id_rsa"
        mode: 0600

    - name: install public key
      copy:
        content: "{{ PUBLIC_SSH_KEY }}"
        dest: "{{ HOME }}/.ssh/id_rsa.pub"
        mode: 0600

    - name: is python3.9 already installed
      stat:
        path: /usr/bin/python3.9
      register: check_python39

    - name: install python 3.9 - step 1
      apt:
        update_cache: yes
      when: not check_python39.stat.exists

    - name: Install python 3.9 - step 2
      apt:
        name: software-properties-common
        state: present
      when: not check_python39.stat.exists

    - name: Install python 3.9 - step 3
      command: add-apt-repository ppa:deadsnakes/ppa
      when: not check_python39.stat.exists

    - name: Install python 3.9 - step 4
      apt:
        name: python3.9
        state: present
      when: not check_python39.stat.exists

    - name: install other packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - diceware
        - docx2txt
        - python3-pip
        - rst2pdf


    - name: is saml2aws already installed
      stat:
        path: /usr/local/bin/saml2aws
      register: stat_saml2aws


    - name: get saml2aws version
      shell: "saml2aws --version | rev | cut -d ' ' -f1 | rev"
      register: saml2aws_version
      when: stat_saml2aws.stat.exists

    # 2.30.0 is the latest saml2aws when this was written.
    - name: check saml2aws version
      get_url:
        url: https://github.com/Versent/saml2aws/releases
        dest: /tmp/releases
        mode: '0440'
      when: not stat_saml2aws.stat.exists or (stat_saml2aws.stat.exists and saml2aws_version.stderr is version('2.30.0', '<'))

    - name: new saml2aws release
      stat:
        path: /tmp/releases
      register: new_release

    - name: get saml2aws path
      shell: grep linux_amd64 /tmp/releases | head -1 | cut -d= -f2 | cut '-d"' -f2
      register: saml2aws_partial_path
      when: new_release.stat.exists

    - name: get saml2aws tar
      get_url:
        url: "{{ 'https://github.com' + saml2aws_partial_path.stdout }}"
        dest: "/tmp/saml2aws.tar"
        mode: '0755'
      when: new_release.stat.exists

    - name: create swml2aws tar directory
      file:
        path: /tmp/saml2aws_dir
        state: directory
      when: new_release.stat.exists

    - name: untar saml2aws
      unarchive:
        src: "/tmp/saml2aws.tar"
        dest: "/tmp/saml2aws_dir"
      when: new_release.stat.exists

    - name: install saml2aws
      copy:
        src: /tmp/saml2aws_dir/saml2aws
        dest: /usr/local/bin/saml2aws
        mode: 755
        owner: root
        group: root
      when: new_release.stat.exists

    - name: cleanup saml2aws directory
      file:
        state: absent
        path: /tmp/saml2aws_dir

    - name: cleanup saml2aws files
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - /tmp/releases
        - /tmp/saml2aws.tar
