#!/usr/bin/env ansible-playbook

- hosts: localhost
  become: yes

  vars:
    - HOME: "{{ ansible_env.HOME }}"

  vars_files:
    - secrets.yml

  tasks:
    - name: install private key
      copy:
        content: "{{ PRIVATE_SSH_KEY }}"
        dest: "{{ HOME }}/.ssh/id_rsa"
        mode: 0600

    - name: install public key
      copy:
        content: "{{ PUBLIC_SSH_KEY }}"
        dest: "{{ HOME }}/.ssh/id_rsa.pub"
        mode: 0600

